#!/usr/bin/env python3
import json

data = {
  "meta": {
    "extracted_at": "2026-05-30T01:23:00+08:00",
    "sources": [
      "dashboard.html localStorage SEED (195 tasks + 26 customers)",
      "dashboard_seed_v2.json (241 products + 5 customers)",
      "替身/客户/ (5份客户画像)",
      "对话/2026-05-29/替身激活/ (决策日志、DACI、词汇产权、评分缺陷等)",
      "site/* (241 HTML页面)",
      "site/vi_quick_ref.css (VI色彩体系)",
      "site/checklist.html (质量清单标准)",
      "site/product_catalog.json (241产品目录)",
      "site/dashboard-v3.html (CSS变量扩展)",
      "/opt/homebrew/lib/node_modules/openclaw/skills/ (58个内置Skill)",
      "~/.openclaw/plugin-skills/ (16个飞书+浏览器Skill)"
    ],
    "total_entries_target": ">= 200"
  },

  "decisions": [
    {"id":"D-0525-1","date":"2026-05-25","decision":"满天星光品牌归属(内部品牌)","driver":"Egbertie","approver":"Egbertie","status":"已确认","category":"品牌"},
    {"id":"D-0527-1","date":"2026-05-27","decision":"评分引擎3模块拆分","driver":"满意红","approver":"满意红","status":"已执行·未记录","category":"技术架构"},
    {"id":"D-0527-2","date":"2026-05-27","decision":"第三条路原则写入","driver":"Egbertie","approver":"Egbertie","status":"已确认","category":"战略"},
    {"id":"D-0527-3","date":"2026-05-27","decision":"YTT蒸馏·28天满天星光整合启动","driver":"满意红","approver":"待Egbertie","status":"待确认","category":"知识资产"},
    {"id":"D-0528-1","date":"2026-05-28","decision":"YTT蒸馏完成·战略建议生成","driver":"满意红","approver":"待Egbertie","status":"待确认","category":"战略"},
    {"id":"D-0528-2","date":"2026-05-28","decision":"241产品全部上线·四关审核通过","driver":"满意红","approver":"满意红","status":"已执行","category":"产品"},
    {"id":"D-0528-3","date":"2026-05-28","decision":"6条关键决策未录入(DACI审计)补录完成","driver":"决策日志替身","approver":"满意红","status":"已修复","category":"治理"},
    {"id":"D-0529-1","date":"2026-05-29","decision":"契晋纪注入首页","driver":"满意红","approver":"满意红","status":"已执行","category":"品牌叙事"},
    {"id":"D-0529-2","date":"2026-05-29","decision":"DACI元治理框架草案","driver":"满意红","approver":"待Egbertie","status":"待确认","category":"治理"},
    {"id":"D-0529-3","date":"2026-05-29","decision":"L1+L2两条腿走路方案维持·否决YTT去图腾化","driver":"满意红","approver":"满意红","status":"已确认","category":"战略"},
    {"id":"D-0529-4","date":"2026-05-29","decision":"暂停产品语言体系去图腾化·YTT词汇不替换满意姐原创IP","driver":"满意红","approver":"满意红","status":"已执行","category":"品牌"},
    {"id":"D-0529-5","date":"2026-05-29","decision":"建立满意解核心词汇产权表(L0/L1/L2分层)","driver":"满意红","approver":"满意红","status":"已执行","category":"知识资产"},
    {"id":"D-0529-6","date":"2026-05-29","decision":"评分引擎3缺陷列入P0代码TODO","driver":"满意红","approver":"满意红","status":"已执行","category":"技术"},
    {"id":"D-0529-7","date":"2026-05-29","decision":"建立Git提交规范·禁止50+文件大提交","driver":"满意红","approver":"满意红","status":"已执行","category":"工程规范"},
    {"id":"D-0529-8","date":"2026-05-29","decision":"设定日志空白=系统级事故规则","driver":"满意红","approver":"满意红","status":"已执行","category":"运维"},
    {"id":"D-0529-9","date":"2026-05-29","decision":"蓝军独立Session启动·17替身全量审核","driver":"满意红","approver":"满意红","status":"已执行","category":"审计"},
    {"id":"D-0529-10","date":"2026-05-29","decision":"VC投后访谈启动(06-01前)需Egbertie审批","driver":"研究咨询师","approver":"待Egbertie","status":"待确认","category":"市场验证"},
    {"id":"D-0529-11","date":"2026-05-29","decision":"产品视觉A/B/C分级+标准化模板","driver":"创意设计师","approver":"待Egbertie","status":"待确认","category":"设计"}
  ],

  "knowledge_assets": [
    {"id":"KA-001","type":"论文·满意姐","name":"SPM-001 满意解决策理论在创业合伙人匹配中的应用","status":"已消化","domain":"决策科学"},
    {"id":"KA-002","type":"论文·满意姐","name":"SPM-002 企业儒学视角下的合伙人伦理治理框架","status":"部分消化","domain":"管理哲学"},
    {"id":"KA-003","type":"论文·满意姐","name":"SPM-003 认知神经科学与商业直觉","status":"引用但未落地","domain":"神经科学"},
    {"id":"KA-004","type":"论文·满意姐","name":"SPM-004 AI Agent系统在创业决策支持中的应用","status":"已消化","domain":"AI系统"},
    {"id":"KA-005","type":"论文·满意姐","name":"SPM-005 五维决策框架的跨文化验证","status":"已消化","domain":"跨文化管理"},
    {"id":"KA-006","type":"论文·满意姐","name":"SPM-006 硬科技转化中的合伙人冲突类型学","status":"部分消化","domain":"创业管理"},
    {"id":"KA-007","type":"论文·满意姐","name":"SPM-007 Token经济学与AI Agent资源治理","status":"已消化","domain":"AI治理"},
    {"id":"KA-008","type":"论文·满意姐","name":"SPM-008 深港双城硬科技生态系统","status":"未消化","domain":"区域经济"},
    {"id":"KA-009","type":"论文·满意姐","name":"SPM-009 合伙人决策成熟度测评系统","status":"已消化","domain":"决策支持"},
    {"id":"KA-010","type":"论文·满意姐","name":"SPM-010 有限理性下的创业合伙人匹配模型","status":"未消化","domain":"决策理论"},
    {"id":"KA-011","type":"论文·满意姐","name":"SPM-011 神经可塑性与商业直觉训练","status":"未消化","domain":"神经科学"},
    {"id":"KA-012","type":"论文·满意姐","name":"SPM-012 基于AI蓝军方法论的合伙协议压力测试","status":"部分消化","domain":"风险管理"},
    {"id":"KA-013","type":"论文·满意姐","name":"SPM-013 满意解研究所方法论综述","status":"已消化","domain":"方法论"},
    {"id":"KA-014","type":"扣子遗产","name":"扣眼系列·三维定位·五字真言·AI能力分级","status":"已消化","domain":"AI方法论"},
    {"id":"KA-015","type":"扣子遗产","name":"8赛道研究(量子/脑机/eVTOL/机器人/芯片/智驾/储能/出海)","status":"部分消化","domain":"产业分析"},
    {"id":"KA-016","type":"扣子遗产","name":"满天星光品牌体系·月路桥钉·四重定位","status":"已消化","domain":"品牌"},
    {"id":"KA-017","type":"扣子遗产","name":"满天星光决策体系·三层决策·ICER·S-O-E·1-3-1","status":"部分消化","domain":"决策"},
    {"id":"KA-018","type":"扣子遗产","name":"28天日志·日常工作记录","status":"未逐天交叉","domain":"运营"},
    {"id":"KA-019","type":"扣子遗产","name":"5封邮件·交叉整合分析","status":"已消化","domain":"通信"},
    {"id":"KA-020","type":"深度学习·W1","name":"Gary Klein自然主义决策(Naturalistic DM)","status":"已完成","domain":"决策科学"},
    {"id":"KA-021","type":"深度学习·W1","name":"Cal Newport深度工作(Deep Work)","status":"已完成","domain":"生产力"},
    {"id":"KA-022","type":"深度学习·W1","name":"Don Norman认知设计","status":"已完成","domain":"设计"},
    {"id":"KA-023","type":"深度学习·W2","name":"Seth Godin部落营销(Tribes)","status":"待执行","domain":"营销"},
    {"id":"KA-024","type":"深度学习·W2","name":"Dieter Rams设计10原则","status":"待执行","domain":"设计"},
    {"id":"KA-025","type":"深度学习·W2","name":"Donella Meadows系统杠杆点","status":"待执行","domain":"系统思维"},
    {"id":"KA-026","type":"深度学习·W3","name":"Annie Duke不确定性决策(Thinking in Bets)","status":"待执行","domain":"决策科学"},
    {"id":"KA-027","type":"深度学习·W3","name":"Grant Sanderson可视化沟通","status":"待执行","domain":"教育"},
    {"id":"KA-028","type":"深度学习·W3","name":"Robert McKee故事结构(Story)","status":"待执行","domain":"叙事"},
    {"id":"KA-029","type":"深度学习·W4","name":"John Boyd OODA循环","status":"待执行","domain":"战略"},
    {"id":"KA-030","type":"深度学习·W4","name":"Sal Khan微学习法","status":"待执行","domain":"教育"},
    {"id":"KA-031","type":"深度学习·W4","name":"Deming质量管理","status":"待执行","domain":"质量"},
    {"id":"KA-032","type":"研究支撑","name":"Simon(1978诺贝尔)·满意解·最优解不存在","status":"已整合","in_product":"checklist.html","domain":"决策理论"},
    {"id":"KA-033","type":"研究支撑","name":"Kahneman(2002诺贝尔)·快思考经常骗你","status":"已整合","in_product":"checklist.html","domain":"认知心理学"},
    {"id":"KA-034","type":"研究支撑","name":"Wasserman(10000+创始人)·73%在最乐观时签最不可逆协议","status":"已整合","in_product":"checklist.html","domain":"创业研究"},
    {"id":"KA-035","type":"研究支撑","name":"Gottman(16年研究)·四骑士·91%准确率","status":"已整合","in_product":"checklist.html","domain":"关系心理学"},
    {"id":"KA-036","type":"研究支撑","name":"Duke·不要用结果反推决策质量","status":"已整合","in_product":"checklist.html","domain":"决策科学"},
    {"id":"KA-037","type":"研究支撑","name":"Lencioni·团队功能障碍5层金字塔","status":"已整合","in_product":"checklist.html","domain":"组织行为"},
    {"id":"KA-038","type":"研究支撑","name":"Feld·VC交易圣经·估值越高条款越危险","status":"已整合","in_product":"checklist.html","domain":"VC/投资"},
    {"id":"KA-039","type":"研究支撑","name":"Moyer·Slicing Pie·股权不是激励是记账","status":"已整合","in_product":"slicing-pie.html","domain":"创业治理"},
    {"id":"KA-040","type":"研究支撑","name":"Dunford·定位不是口号是你在哪个世界里最好","status":"已整合","in_product":"checklist.html","domain":"品牌定位"},
    {"id":"KA-041","type":"研究支撑","name":"Damasio·身体在决策前就已经在投票","status":"已整合","in_product":"pre0.html","domain":"神经科学"},
    {"id":"KA-042","type":"研究支撑","name":"Klein·RPD模型·专家直觉是模式识别","status":"已整合","in_product":"checklist.html","domain":"决策科学"}
  ],

  "skills_instruction_set": [
    {"id":"SK-001","name":"canvas","category":"系统工具","desc":"Canvas HTML呈现与调试"},
    {"id":"SK-002","name":"coding-agent","category":"系统工具","desc":"委托编码给Codex/Claude Code/OpenCode"},
    {"id":"SK-003","name":"diagram-maker","category":"创作工具","desc":"SVG/HTML或Excalidraw图表"},
    {"id":"SK-004","name":"healthcheck","category":"运维","desc":"审计加固OpenClaw主机"},
    {"id":"SK-005","name":"meme-maker","category":"创作工具","desc":"梗图模板搜索与生成"},
    {"id":"SK-006","name":"nano-pdf","category":"创作工具","desc":"自然语言指令编辑PDF"},
    {"id":"SK-007","name":"node-connect","category":"运维","desc":"诊断节点配对连接"},
    {"id":"SK-008","name":"node-inspect-debugger","category":"开发","desc":"Node.js debugger"},
    {"id":"SK-009","name":"python-debugpy","category":"开发","desc":"Python debugpy远程调试"},
    {"id":"SK-010","name":"skill-creator","category":"系统工具","desc":"创建编辑审计SKILL.md"},
    {"id":"SK-011","name":"spike","category":"开发","desc":"快速原型验证可行性"},
    {"id":"SK-012","name":"taskflow","category":"系统工具","desc":"多步骤TaskFlow作业协调"},
    {"id":"SK-013","name":"taskflow-inbox-triage","category":"系统工具","desc":"收件箱分类·意图路由"},
    {"id":"SK-014","name":"weather","category":"生活工具","desc":"天气查询wttr.in"},
    {"id":"SK-015","name":"tavily","category":"搜索工具","desc":"Tavily网络搜索"},
    {"id":"SK-016","name":"1password","category":"安全","desc":"密码管理"},
    {"id":"SK-017","name":"apple-notes","category":"笔记","desc":"Apple Notes集成"},
    {"id":"SK-018","name":"apple-reminders","category":"生活工具","desc":"Apple Reminders"},
    {"id":"SK-019","name":"bear-notes","category":"笔记","desc":"Bear笔记"},
    {"id":"SK-020","name":"blogwatcher","category":"内容","desc":"博客监控"},
    {"id":"SK-021","name":"blucli","category":"系统工具","desc":"Bluetooth CLI"},
    {"id":"SK-022","name":"camsnap","category":"生活工具","desc":"摄像头快照"},
    {"id":"SK-023","name":"clawhub","category":"系统工具","desc":"OpenClaw Hub"},
    {"id":"SK-024","name":"discord","category":"通信","desc":"Discord消息交互"},
    {"id":"SK-025","name":"eightctl","category":"系统工具","desc":"Eight睡眠控制器"},
    {"id":"SK-026","name":"gemini","category":"AI","desc":"Gemini模型"},
    {"id":"SK-027","name":"gh-issues","category":"开发","desc":"GitHub Issues"},
    {"id":"SK-028","name":"gifgrep","category":"创作工具","desc":"GIF搜索"},
    {"id":"SK-029","name":"github","category":"开发","desc":"GitHub仓库操作"},
    {"id":"SK-030","name":"gog","category":"生活工具","desc":"GoG游戏平台"},
    {"id":"SK-031","name":"goplaces","category":"生活工具","desc":"地点管理"},
    {"id":"SK-032","name":"himalaya","category":"通信","desc":"CLI邮件客户端"},
    {"id":"SK-033","name":"imsg","category":"通信","desc":"iMessage集成"},
    {"id":"SK-034","name":"mcporter","category":"生活工具","desc":"Minecraft端口"},
    {"id":"SK-035","name":"model-usage","category":"AI","desc":"模型用量统计"},
    {"id":"SK-036","name":"notion","category":"笔记","desc":"Notion集成"},
    {"id":"SK-037","name":"obsidian","category":"笔记","desc":"Obsidian集成"},
    {"id":"SK-038","name":"openai-whisper","category":"AI","desc":"OpenAI语音转文字"},
    {"id":"SK-039","name":"openai-whisper-api","category":"AI","desc":"Whisper API"},
    {"id":"SK-040","name":"openhue","category":"生活工具","desc":"Philips Hue灯光"},
    {"id":"SK-041","name":"oracle","category":"AI","desc":"AI咨询问答"},
    {"id":"SK-042","name":"ordercli","category":"生活工具","desc":"CLI订单管理"},
    {"id":"SK-043","name":"peekaboo","category":"生活工具","desc":"隐私屏幕遮挡"},
    {"id":"SK-044","name":"sag","category":"AI","desc":"ElevenLabs TTS语音合成"},
    {"id":"SK-045","name":"session-logs","category":"系统工具","desc":"会话日志管理"},
    {"id":"SK-046","name":"sherpa-onnx-tts","category":"AI","desc":"本地TTS引擎"},
    {"id":"SK-047","name":"slack","category":"通信","desc":"Slack消息交互"},
    {"id":"SK-048","name":"songsee","category":"生活工具","desc":"音乐识别"},
    {"id":"SK-049","name":"sonoscli","category":"生活工具","desc":"Sonos音响"},
    {"id":"SK-050","name":"spotify-player","category":"生活工具","desc":"Spotify播放"},
    {"id":"SK-051","name":"summarize","category":"AI","desc":"内容摘要"},
    {"id":"SK-052","name":"things-mac","category":"生活工具","desc":"Things任务管理"},
    {"id":"SK-053","name":"tmux","category":"开发","desc":"Tmux终端复用"},
    {"id":"SK-054","name":"trello","category":"笔记","desc":"Trello看板"},
    {"id":"SK-055","name":"video-frames","category":"创作工具","desc":"视频逐帧提取"},
    {"id":"SK-056","name":"voice-call","category":"通信","desc":"语音通话"},
    {"id":"SK-057","name":"wacli","category":"通信","desc":"WhatsApp CLI"},
    {"id":"SK-058","name":"xurl","category":"系统工具","desc":"URL短链接"},
    {"id":"SK-059","name":"browser-automation","category":"系统工具","desc":"浏览器自动化"},
    {"id":"SK-060","name":"feishu-bitable","category":"飞书","desc":"多维表格·27字段"},
    {"id":"SK-061","name":"feishu-calendar","category":"飞书","desc":"日历日程"},
    {"id":"SK-062","name":"feishu-channel-rules","category":"飞书","desc":"频道输出规则"},
    {"id":"SK-063","name":"feishu-create-doc","category":"飞书","desc":"创建云文档"},
    {"id":"SK-064","name":"feishu-doc","category":"飞书","desc":"文档读写"},
    {"id":"SK-065","name":"feishu-drive","category":"飞书","desc":"云空间文件管理"},
    {"id":"SK-066","name":"feishu-fetch-doc","category":"飞书","desc":"获取文档Markdown"},
    {"id":"SK-067","name":"feishu-im-read","category":"飞书","desc":"IM消息·话题回复"},
    {"id":"SK-068","name":"feishu-perm","category":"飞书","desc":"文档权限"},
    {"id":"SK-069","name":"feishu-task","category":"飞书","desc":"任务查询"},
    {"id":"SK-070","name":"feishu-troubleshoot","category":"飞书","desc":"问题排查"},
    {"id":"SK-071","name":"feishu-update-doc","category":"飞书","desc":"文档更新7种模式"},
    {"id":"SK-072","name":"feishu-wiki","category":"飞书","desc":"知识库"},
    {"id":"SK-073","name":"sri-driver-dashboard","category":"满意解内部","desc":"195任务·26客户·BSD算法·驾驶舱","source":"dashboard.html"},
    {"id":"SK-074","name":"sri-quality-gate","category":"满意解内部","desc":"L0L1审核·四关通过率·商标注册","source":"dash_quality"},
    {"id":"SK-075","name":"sri-growth-flywheel","category":"满意解内部","desc":"飞轮·线上产品·活跃客户30d","source":"dash_growth"},
    {"id":"SK-076","name":"sri-avatars-system","category":"满意解内部","desc":"23替身·五路图腾·客户替身5类","source":"dashboard.html"},
    {"id":"SK-077","name":"sri-product-taxonomy","category":"满意解内部","desc":"章衡镜契觉·五维决策·满意解","source":"dashboard.html"},
    {"id":"SK-078","name":"sri-decision-checklist","category":"满意解内部","desc":"6步自检·12源验证·20分钟","source":"checklist.html"},
    {"id":"SK-079","name":"sri-product-audit","category":"满意解内部","desc":"四关审核·产品评级·241产品","source":"product_catalog.json"},
    {"id":"SK-080","name":"sri-daci-governance","category":"满意解内部","desc":"DACI·S/A/B/C决策·蓝军Session","source":"DACI元治理框架"}
  ],

  "content_assets": {
    "total_pages": 241,
    "classification": {
      "入口页": 3,
      "工具页": 30,
      "教育页": 70,
      "游戏页": 7,
      "运营页": 26,
      "媒体页": 6,
      "赛道页": 6,
      "公众号文章": 7,
      "案例页": 8,
      "产品页": 4,
      "测试页": 3,
      "管理页": 9,
      "参考页": 23,
      "专用页": 10,
      "对话页": 29
    },
    "family_distribution": {"章": 0, "衡": 8, "镜": 12, "契": 9, "觉": 8, "其他": 204},
    "key_pages": {
      "入口": ["index.html", "go.html", "gate.html"],
      "核心工具": ["assessment.html", "checklist.html", "radar.html", "fulldiag.html", "thermometer.html", "decision-theatre.html"],
      "系统管理": ["dashboard.html", "admin.html", "account.html", "product-catalog.html"]
    }
  },

  "vi_standards": {
    "source": "品牌视觉识别手册终稿完整版 V1.0 (2026年4月)",
    "feishu_doc_id": "LCZDdJ0afoPtEGxWkkQcNZDgnsc",
    "core_principle": "火承土印·金石拓印·赭石红唯一性",
    "color_system": {
      "primary": {"name": "赭石红 Terracotta Red", "var": "--sri-red", "hex": "#C23B22", "usage": "唯一主色·强调·按钮·标题"},
      "background": {"name": "米白/宣纸白 Rice Paper", "var": "--sri-cream", "hex": "#F5F0E6", "usage": "全局底色"},
      "text_body": {"name": "正文深灰 Charcoal", "var": "--sri-dark", "hex": "#4A4A4A"},
      "text_heading": {"name": "标题炭黑 Deep Charcoal", "var": "--sri-black", "hex": "#2A2A2A"},
      "accent": {"name": "暗金 Antique Gold", "var": "--sri-gold", "hex": "#B8860B", "usage": "仅可行域/左脑逻辑点缀"},
      "border": {"name": "暖边界", "var": "--sri-border", "hex": "#D4C5A0"},
      "functional_success": {"hex": "#3D7A4F", "usage": "达标绿"},
      "functional_warning": {"hex": "#C2780A", "usage": "警示金"}
    },
    "prohibitions": ["正红", "橘红", "蓝做主色", "绿做主色", "橙做主色", "将13个符号随意更改颜色"],
    "typography": {
      "sans": "-apple-system, PingFang SC, Microsoft YaHei, sans-serif",
      "serif": "Noto Serif SC, Source Han Serif SC, Georgia, serif"
    },
    "spacing_scale": {"xs": "4px", "sm": "8px", "md": "16px", "lg": "24px", "xl": "32px", "2xl": "48px"},
    "radius_scale": {"sm": "8px", "md": "12px", "lg": "14px"},
    "product_visual_quality": "创意设计师建议A/B/C三级分级·241产品视觉质量参差不齐",
    "metaphors": ["米白=纸产品隐喻", "暗金=方法论历史深度"]
  },

  "quality_metrics": [
    {"id": "QM-001", "standard": "L0提案审核", "status": "待执行", "priority": "P0"},
    {"id": "QM-002", "standard": "L1方法论审核", "status": "55%", "priority": "P0"},
    {"id": "QM-003", "standard": "四关通过率≥80%", "status": "96%", "priority": "P0"},
    {"id": "QM-004", "standard": "商标注册", "status": "未申请", "priority": "P0"},
    {"id": "QM-005", "standard": "四关审核:功能", "status": "已通过"},
    {"id": "QM-006", "standard": "四关审核:内容", "status": "已通过"},
    {"id": "QM-007", "standard": "四关审核:安全", "status": "已通过"},
    {"id": "QM-008", "standard": "四关审核:VI", "status": "已通过"},
    {"id": "QM-009", "standard": "DQI权重灵敏度分析", "status": "待修复", "severity": "P0", "ref": "ENG-001"},
    {"id": "QM-010", "standard": "MRI置信区间", "status": "待修复", "severity": "P0", "ref": "ENG-002"},
    {"id": "QM-011", "standard": "飞轮75%设计文档缺失", "status": "待修复", "severity": "P0", "ref": "ENG-003"},
    {"id": "QM-012", "standard": "Git提交规范:一次提交=一个逻辑变更", "status": "已生效", "date": "2026-05-29"},
    {"id": "QM-013", "standard": "Git债务:128次提交需补changelog", "status": "P2", "severity": "P2"},
    {"id": "QM-014", "standard": "日志空白=系统级事故", "status": "已生效", "date": "2026-05-29"},
    {"id": "QM-015", "standard": "蓝军独立Session审计(每3天1次)", "status": "已触发", "date": "2026-05-29"},
    {"id": "QM-016", "standard": "CHECKLIST·PRE-0状态校准(3题)", "status": "已上线", "source": "checklist.html"},
    {"id": "QM-017", "standard": "CHECKLIST·五维快速自检(5维1-5分)", "status": "已上线", "source": "checklist.html"},
    {"id": "QM-018", "standard": "CHECKLIST·Gottman四骑士检测", "status": "已上线", "source": "checklist.html"},
    {"id": "QM-019", "standard": "CHECKLIST·Lencioni金字塔定位(5层)", "status": "已上线", "source": "checklist.html"},
    {"id": "QM-020", "standard": "CHECKLIST·决策行动分级(R/A/Y/G)", "status": "已上线", "source": "checklist.html"},
    {"id": "QM-021", "standard": "CHECKLIST·延时复核(24h重检)", "status": "已上线", "source": "checklist.html"},
    {"id": "QM-022", "standard": "产品星级评定", "status": "待开始", "milestone": "06-14"},
    {"id": "QM-023", "standard": "来源标注补齐", "status": "进行中", "milestone": "06-07"},
    {"id": "QM-024", "standard": "夏至路演准备", "status": "进行中", "milestone": "06-21"}
  ],

  "lifecycle_stages": [
    {"id": "LC-001", "stage": "完成", "name": "产品命名体系", "date": "05-28"},
    {"id": "LC-002", "stage": "完成", "name": "233产品上线", "date": "05-28"},
    {"id": "LC-003", "stage": "完成", "name": "产品标准体系", "date": "05-28"},
    {"id": "LC-004", "stage": "完成", "name": "驾驶舱中枢", "date": "05-29"},
    {"id": "LC-005", "stage": "完成", "name": "增长飞轮引擎", "date": "05-28"},
    {"id": "LC-006", "stage": "完成", "name": "密码门控体系", "date": "05-28"},
    {"id": "LC-007", "stage": "进行中", "name": "来源标注补齐", "date": "06-07"},
    {"id": "LC-008", "stage": "待开始", "name": "产品星级评定", "date": "06-14"},
    {"id": "LC-009", "stage": "进行中", "name": "夏至路演准备", "date": "06-21"},
    {"id": "LC-010", "stage": "待执行", "name": "夏至官宣日", "date": "06-21"},
    {"id": "LC-011", "layer": "L1文明", "name": "13个符号全量定位"},
    {"id": "LC-012", "layer": "L1文明", "name": "两翼三脉产品线展开"},
    {"id": "LC-013", "layer": "L1文明", "name": "火承土印因果律实现"},
    {"id": "LC-014", "layer": "L1文明", "name": "金石拓印版本年轮"},
    {"id": "LC-015", "layer": "L1文明", "name": "米白=纸产品隐喻·暗金=方法论历史深度"},
    {"id": "LC-016", "layer": "L2根系", "name": "68Entry->决策剧场场景映射"},
    {"id": "LC-017", "layer": "L2根系", "name": "8赛道参数->评分引擎校准"},
    {"id": "LC-018", "layer": "L2根系", "name": "扣子6创业者公式->客户模拟"},
    {"id": "LC-019", "layer": "L2根系", "name": "12x8冲突矩阵->审核标准"},
    {"id": "LC-020", "layer": "L3土壤", "name": "日起课->驾驶舱自动同步"},
    {"id": "LC-021", "layer": "L3土壤", "name": "飞轮日报->三人协作者"},
    {"id": "LC-022", "layer": "L3土壤", "name": "翻书自动代谢通道"},
    {"id": "LC-023", "layer": "L3土壤", "name": "单向门清单确立"},
    {"id": "LC-024", "layer": "L3土壤", "name": "知识债务自动追踪"},
    {"id": "LC-025", "layer": "L4骨架", "name": "评分引擎真实数据通道"},
    {"id": "LC-026", "layer": "L4骨架", "name": "矛盾热力图动态化"},
    {"id": "LC-027", "layer": "L4骨架", "name": "决策剧场真实数据场景"},
    {"id": "LC-028", "layer": "L4骨架", "name": "干预方案模板引擎"},
    {"id": "LC-029", "layer": "L4骨架", "name": "产品Roadmap生成"},
    {"id": "LC-030", "layer": "L5枝叶", "name": "DQI双引擎仪表盘"},
    {"id": "LC-031", "layer": "L5枝叶", "name": "MRI引擎自评报告"},
    {"id": "LC-032", "layer": "L5枝叶", "name": "TI信任指数统一度量"},
    {"id": "LC-033", "layer": "L5枝叶", "name": "CI相变曲线可视化"},
    {"id": "LC-034", "layer": "L6生长", "name": "替身自动知识分配"},
    {"id": "LC-035", "layer": "L6生长", "name": "替身生长日志"},
    {"id": "LC-036", "layer": "L6生长", "name": "联合审核标准自动繁殖"},
    {"id": "LC-037", "layer": "L6生长", "name": "替身休眠唤醒机制"},
    {"id": "LC-038", "layer": "L7生态", "name": "每周三生态审计"},
    {"id": "LC-039", "layer": "L7生态", "name": "客户数据回流物理仓库"},
    {"id": "LC-040", "layer": "L7生态", "name": "年度行业报告雏形"}
  ],

  "governance_frameworks": [
    {
      "id": "GF-001",
      "name": "DACI元治理框架",
      "version": "V1.0草案",
      "date": "2026-05-29",
      "description": "满意解研究所内部决策权边界定义",
      "levels": [
        {"